//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENSEK_MeterReading.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ENSEKMeterReadingEntities : DbContext
    {
        public ENSEKMeterReadingEntities()
            : base("name=ENSEKMeterReadingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Meter_Reading> Meter_Reading { get; set; }
        public DbSet<Test_Accounts> Test_Accounts { get; set; }
    }
}
