//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENSEK_MeterReading.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test_Accounts
    {
        public Test_Accounts()
        {
            this.Meter_Reading = new HashSet<Meter_Reading>();
        }
    
        public int AccountId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    
        public virtual ICollection<Meter_Reading> Meter_Reading { get; set; }
    }
}
